# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Develop
- Production

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    short_hash=`git rev-parse --short=7 HEAD`
    echo ""
    echo "Full git hash:  $(Build.SourceVersion)"
    echo "Short git hash: $short_hash"
    echo ""
    ## Fail step if full hash does not start with short hash
    if [[ $(Build.SourceVersion) != $short_hash* ]]; then
      echo "--> Hashes do not match! Aborting."
      exit 1
    fi
    echo "--> Hashes match. Storing short hash for subsequent steps."
    ## Store variable for subsequent steps
    echo "##vso[task.setvariable variable=short_hash]$short_hash"
  workingDirectory: $(Build.SourcesDirectory)
  displayName: Get short git hash
#- task: Docker@2
#  inputs:
#    command: 'build'
#    Dockerfile: '**/Dockerfile'
#    tags: 'celestial-interview-app:$(Build.SourceBranchName)-$short_hash'

